# phantom_node.py
# Part of the PHANTOM Autonomous Living Defense Mesh
# Generated by Synapse Core

import os, time, json, hashlib, threading, secrets, socket, subprocess
from cryptography.fernet import Fernet

TTL = 30                # seconds
ENERGY_COST = 2         # CPU cycles per heartbeat
FITNESS_THRESHOLD = 10  # points needed to replicate

class PhantomAgent:
    def __init__(self, genesis=False):
        self.id = secrets.token_hex(8)
        self.energy = 100
        self.fitness = 0
        self.last_seen = time.time()
        self.config_hash = self._hash_source()
        self.peers = []
        self.key = Fernet.generate_key()
        self.cipher = Fernet(self.key)
        self.genesis = genesis

    # Task 1 – Digital Metabolism
    def heartbeat(self):
        while True:
            self.energy -= ENERGY_COST
            if self.energy <= 0 or (time.time() - self.last_seen) > TTL:
                self.apoptosis()
            self.last_seen = time.time()
            self._scan_anomaly()
            self._mesh_broadcast({"type": "alive", "id": self.id})
            time.sleep(1)

    def apoptosis(self):
        print(f"[{self.id}] apoptosis")
        os._exit(0)

    # Task 2 – Evolutionary Selection
    def _scan_anomaly(self):
        # Mock: detect unauthorized packet
        if secrets.randbelow(100) < 5:
            self.fitness += 1
            print(f"[{self.id}] fitness={self.fitness}")
            if self.fitness >= FITNESS_THRESHOLD:
                self.clone()

    def clone(self):
        subprocess.Popen(["python", __file__, "child"])
        print(f"[{self.id}] replicated")

    # Task 3 – Mesh Distress Protocol
    def _mesh_broadcast(self, msg):
        for peer in self.peers:
            try:
                sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
                enc = self.cipher.encrypt(json.dumps(msg).encode())
                sock.sendto(enc, (peer, 9000))
            except:
                pass

    def listen(self):
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        s.bind(("", 9000))
        while True:
            data, addr = s.recvfrom(1024)
            try:
                msg = json.loads(self.cipher.decrypt(data))
                if msg["type"] == "pain":
                    self._escalate()
            except:
                pass

    def _escalate(self):
        # rotate port / raise encryption
        print(f"[{self.id}] escalating defenses")

    # Task 4 – Polymorphic Identity
    def _hash_source(self):
        try:
            with open(__file__, "rb") as f:
                return hashlib.sha256(f.read()).hexdigest()
        except:
            return "hash_error"

    def mutate(self):
        # rewrite own file with randomized variable names
        try:
            with open(__file__) as f:
                src = f.read()
            noise = secrets.token_hex(4)
            # Simple demonstration of mutation
            src = src.replace("self.energy", f"self.e{noise}")
            with open(__file__, "w") as f:
                f.write(src)
            self.config_hash = self._hash_source()
        except:
            pass

if __name__ == "__main__":
    agent = PhantomAgent(genesis=True)
    threading.Thread(target=agent.heartbeat, daemon=True).start()
    threading.Thread(target=agent.listen, daemon=True).start()
    print(f"PHANTOM Node [{agent.id}] Initialized. Monitoring mesh...")
    while True:
        time.sleep(secrets.randbelow(60))
        agent.mutate()
